# Generated by Django 5.1.1 on 2024-10-29 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('published', models.DateField()),
                ('link', models.URLField()),
                ('transcript', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Yarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('colour', models.CharField(choices=[('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Blue', 'Blue'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Brown', 'Brown'), ('Black', 'Black'), ('White', 'White'), ('Grey', 'Grey')], max_length=50)),
                ('material', models.CharField(choices=[('Wool', 'Wool'), ('Cotton', 'Cotton'), ('Acrylic', 'Acrylic'), ('Polyester', 'Polyester')], max_length=50)),
                ('price', models.FloatField()),
                ('yardage', models.IntegerField()),
                ('hook_size', models.FloatField()),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_started', models.DateField()),
                ('date_finished', models.DateField()),
                ('notes', models.TextField()),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pattern')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectYarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('yarn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.yarn')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='yarn',
            field=models.ManyToManyField(through='api.ProjectYarn', to='api.yarn'),
        ),
    ]
