# Generated by Django 5.1.1 on 2024-10-29 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yarn',
            name='available',
        ),
        migrations.AddField(
            model_name='project',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PatternYarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pattern')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('yarn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.yarn')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='yarn',
            field=models.ManyToManyField(through='api.PatternYarn', to='api.yarn'),
        ),
        migrations.DeleteModel(
            name='ProjectYarn',
        ),
    ]
