# Generated by Django 5.1.1 on 2024-10-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_yarn_available_project_finished_patternyarn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='yarns',
            field=models.ManyToManyField(through='api.PatternYarn', to='api.yarn'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
