# Generated by Django 5.1.1 on 2024-10-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pattern_yarns_alter_pattern_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patternyarn',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='yarn',
        ),
    ]
