# Generated by Django 5.1.1 on 2024-10-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_patternyarn_project_remove_project_yarn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarn',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
