# Generated by Django 5.1.1 on 2024-11-04 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_yarn_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='yarns',
        ),
        migrations.RemoveField(
            model_name='patternyarn',
            name='pattern',
        ),
        migrations.AddField(
            model_name='patternyarn',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_yarns', to='api.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='yarns',
            field=models.ManyToManyField(related_name='projects', through='api.PatternYarn', to='api.yarn'),
        ),
        migrations.AlterField(
            model_name='patternyarn',
            name='yarn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yarn_projects', to='api.yarn'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_finished',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.pattern'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.user'),
        ),
    ]
