# Generated by Django 5.1.1 on 2024-11-04 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_pattern_yarns_remove_patternyarn_pattern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patternyarn',
            name='pattern',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pattern_yarns', to='api.pattern'),
        ),
        migrations.AlterField(
            model_name='patternyarn',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_yarns', to='api.project'),
        ),
        migrations.AlterField(
            model_name='patternyarn',
            name='yarn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yarn_patterns', to='api.yarn'),
        ),
    ]
